//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heros
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AC { get; set; }
        public string Property1 { get; set; }
        public string Dex { get; set; }
        public string Class { get; set; }
        public string Description { get; set; }
    }
}
