//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monsters
    {
        public int MonsterId { get; set; }
        public string Name { get; set; }
        public string ArmorClass { get; set; }
        public string HitPoints { get; set; }
        public string Dex { get; set; }
        public string Description { get; set; }
        public string CP { get; set; }
    }
}
